name = "LossFunctions"
uuid = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
version = "1.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"

[extensions]
LossFunctionsCategoricalArraysExt = "CategoricalArrays"

[compat]
CategoricalArrays = "0.10, 1.0"
julia = "1.9"

[extras]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
